- .eslintrc.yml
- .gitignore
- Jenkinsfile
- README.md
- package-lock.json
- package.json
- scripts/install-zowe.sh
- scripts/temp-fixes-after-install.sh
- scripts/temp-fixes-before-install.sh
- scripts/temp-fixes-prereqs-image.sh
- test/cli/test-version.js
- test/cli/test-zosmf.js
- test/cli/utils.js
- test/install/test-explorer-server.js
- test/install/test-installed-files.js
- test/install/test-zlux-server.js
> resync before migration

- Jenkinsfile
- package-lock.json
- package.json
- scripts/refresh-zosaas.sh
- scripts/temp-fixes-after-install.sh
- test/e2e/test-01-login.js
- test/e2e/test-02-jes-explorer.js
- test/e2e/test-03-mvs-explorer.js
- test/e2e/test-04-uss-explorer.js
- test/e2e/test-07-iframe.js
- test/e2e/test-09-helloworld.js
- test/e2e/utils.js
- test/install/test-zlux-server.js
- test/mocha.opts
- #10: fully automate zD&T refresh
- #19: fix test cases for v0.9.1
> issue #10 and issue #19

- test/e2e/test-02-jes-explorer.js
- test/e2e/utils.js
> fix jes explorer test failure

- scripts/uninstall-zowe.sh
> improve uninstall script

- Jenkinsfile
- test/explorer/test-api-datasets.js
- test/explorer/test-api-jobs.js
- test/explorer/test-api-system.js
- test/explorer/test-api-uss.js
- test/explorer/test-api-zos.js
- test/explorer/test-docs.js
> explorer server url changed

- test/explorer/test-api-datasets.js
- test/explorer/test-api-jobs.js
- test/explorer/test-api-system.js
- test/explorer/test-api-uss.js
- test/explorer/test-api-zos.js
- test/explorer/test-docs.js
Signed-off-by: Colin-Stone <30794003+Colin-Stone@users.noreply.github.com>
Sorry Jack you to this before me. I hadn't intended to let these changes out until 0.9.3 but 0.9.2 had not left the station.
> Need to specify correct API reference

- Jenkinsfile
> remove extra api in url

- scripts/install-zowe.sh
> passing correct params to fix script

- scripts/install-zowe.sh
- scripts/temp-fixes-after-install.sh
- scripts/temp-fixes-before-install.sh
> run pre/post install verify

- test/cli/test-04-files.js
Signed-off-by: MarkAckert <Mark.Ackert@ca.com>
> Fix CLI Test

- scripts/temp-fixes-after-install.sh
- test/e2e/test-03-mvs-explorer.js
- test/e2e/test-04-uss-explorer.js
- test/explorer/test-api-uss.js
- test/install/test-zlux-server.js
Signed-off-by: Colin-Stone <30794003+Colin-Stone@users.noreply.github.com>
Jack.. I noticed the sniff test had failed for this build. Although I'm not familiar with the tests I think these are the required changes
> Update sniff testing

- test/e2e/test-03-mvs-explorer.js
- test/e2e/utils.js
- test/install/test-zlux-server.js
The zowe build `libs-snapshot-local/com/project/zowe/0.9.6-STANDALONE-MVS/zowe-0.9.6-20190110.154049-2.pax` is created and passed smoke test `https://wash.zowe.org:8443/job/zowe-install-test/job/fix-mvs-tests/3/console`.
> Fix mvs tests

- test/e2e/test-09-editor.js
- test/e2e/test-11-workflows.js
- test/e2e/test-12-angular-sample.js
- test/e2e/test-13-react-sample.js
Covered applications:
- Editor
- Workflows
- Angular Sample
- React Sample
Signed-off-by: Dmitry Nikolaev <dnikolaev@rocketsoftware.com>
> Add smoke Selenium tests for zLUX apps

- .gitignore
- Jenkinsfile
- sonar-project.properties
- test/e2e/test-01-login.js
- test/e2e/utils.js
> Issue #13: add sonar scan and fix major issues

- Jenkinsfile
- scripts/install-zowe.sh
> use abbr to reduce command line characters

- Jenkinsfile
> determine if api catalog is started

- test/e2e/test-03-mvs-explorer.js
> enable mvs explorer tests

- Jenkinsfile
> use dind label

- Jenkinsfile
> fix with cli bundle name change

- scripts/temp-fixes-after-install.sh
> replace host name in explorer server config

- test/explorer/test-api-datasets.js
- test/explorer/test-api-jobs.js
> Attempt to update api responses

- scripts/uninstall-zowe.sh
> use P to stop zwesis01

- scripts/AZWE001.README.jcl
- scripts/install-SMPE-PAX.sh
This PR updates the PAX shell script and adds a sample JCL job based on the README.  Both have been tested and worked.  They are for information, and will be subject to modifications before being added to the build pipeline.
> Tailor smpe

- Jenkinsfile
@John-A-Davies please check the FIXME lines, I added some comments there.
> smpe install prototype

- scripts/install-SMPE-PAX.sh
Signed-off-by: John Davies <daviesja@uk.ibm.com>
> update SMPE install script

- scripts/install-SMPE-PAX.sh
The `install-SMPE-PAX.sh` scripts needs to edit its input JCL.  Previously the sed scripts to do this were external.  This PR folds them into the main script, allowing the sed scripts to derive its replacement strings from the parameter list of `install-SMPE-PAX.sh`, instead of being hard-coded.
> insert sed scripts in install script

- scripts/install-SMPE-PAX.sh
Signed-off-by: John Davies <daviesja@uk.ibm.com>
This PR changes the script to take the EBCDIC version of the README JCL instead of the ASCII one. 
It also 
1 handles extra information on the job submission message
2 takes the opercmd from the right place
3 Accepts the current GIMUNZIP control statements
> Accept EBCDIC README JCL file instead of ASCII, plus 2 minor corrections

- scripts/install-SMPE-PAX.sh
Signed-off-by: John Davies <daviesja@uk.ibm.com>
I made some minor changes to make this work on MV3B with the current pax.Z file.
> Minor fixes to allow install-SMPE-PAX.sh to consume pax.Z file

- scripts/install-zowe.sh
> wait for xmem server fully started

- scripts/install-config-marist.sh
- scripts/install-config-river.sh
- scripts/install-zowe.sh
- scripts/temp-fixes-after-started.sh
- scripts/uninstall-zowe.sh
> customize user dir

- test/e2e/test-02-jes-explorer.js
> test izusvr instead of zowe jobs

- test/e2e/test-04-uss-explorer.js
> re-enable uss explorer test

- Jenkinsfile
- scripts/install-zowe.sh
- scripts/uninstall-zowe.sh
- test/install/test-installed-files.js
> Update tests to reflect zowe-start and stop change

- Jenkinsfile
> clean up node_modules folder

- scripts/uninstall-zowe.sh
**Note: before we fix the parmlib conflict in the build and installation, this test will fail.**
> properly remove zss xmem parmlib

- scripts/uninstall-zowe.sh
Fix KNOWN_XMEM_JOB_NAMES="ZWESIS01 ZWEXMSTC ZWESISTC" in `uninstall-zowe.sh`
> Add another known xmem job name

- scripts/uninstall-zowe.sh
Related to https://github.com/zowe/zowe-install-packaging/issues/941
> delete facility profiles

- scripts/install-zowe.sh
Part of https://github.com/zowe/zowe-install-packaging/issues/957
> Remove duplicate install proc

- Jenkinsfile
> add option to test different node versions (issue #955)

- Jenkinsfile
> support zowe-smpe.zip format

- Jenkinsfile
- scripts/temp-fixes-after-started.sh
> Remove zowe-verify

- Jenkinsfile
> add node.js v8.17.0

- test/cli/test-01-version.js
- test/cli/test-04-files.js
Update cli tests to match new version
> Test compat with cli updates

- scripts/install-zowe.sh
> Update log location
